# Generated by Django 5.2 on 2025-11-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runs",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "init"),
                    ("in_progress", "in_progress"),
                    ("finished", "finished"),
                ],
                default="init",
            ),
        ),
    ]
