# Generated by Django 5.2 on 2025-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_runs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=9, null=True),
        ),
    ]
