# Generated by Django 5.2 on 2025-11-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_runs_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
