# Generated by Django 5.2 on 2025-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_runs_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
