# Generated by Django 5.2 on 2025-11-17 05:47

import project_run.apps.positions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7, validators=[project_run.apps.positions.models.validate_latitude])),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7, validators=[project_run.apps.positions.models.validate_longitude])),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('picture', models.URLField()),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
