# Generated by Django 5.2 on 2025-11-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectibleitems', '0002_userscollectionsitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectibleitems',
            name='created_at',
        ),
    ]
