# Generated by Django 5.2 on 2025-11-15 14:17

import project_run.apps.athletes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(default=1, validators=[project_run.apps.athletes.models.validate_weight]),
        ),
    ]
