# Generated by Django 5.2 on 2025-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_alter_athleteinfo_goals_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.FloatField(default=0),
        ),
    ]
