# Generated by Django 5.2 on 2025-11-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athleteinfo_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(null=True),
        ),
    ]
