# Generated by Django 5.2 on 2025-11-16 08:08

import project_run.apps.athletes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_alter_athleteinfo_goals'),
    ]
    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.IntegerField(default=1, null=True, validators=[project_run.apps.athletes.models.validate_weight]),
        ),
    ]
