# Generated by Django 5.2 on 2025-11-20 14:56

import project_run.apps.subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[project_run.apps.subscriptions.models.min_rating_validator, project_run.apps.subscriptions.models.max_rating_validator]),
        ),
    ]
