# Generated by Django 5.2 on 2025-11-17 05:47

import project_run.apps.positions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[project_run.apps.positions.models.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='positions',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[project_run.apps.positions.models.validate_longitude]),
        ),
    ]
