# Generated by Django 5.2 on 2025-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_positions_latitude_alter_positions_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
