# Generated by Django 5.2 on 2025-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_alter_positions_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='positions',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
